### PR TITLE
Add partition size parameter to SparkPersistor

### PR DESCRIPTION
**Pull request by zhenyu**
## Overview
This PR exposes the partition size as a parameter for the `persist_wicker_dataset` in the spark plugin instead of a hard-coded `SPARK_PARTITION_SIZE` const. To make the interface backward compatible, the parameter is set by default to the same value as the original const value. We also rename the const as `SPARK_PARTITION_SIZE` to `DEFAULT_SPARK_PARTITION_SIZE` to reflect the change.

## Notes
- This is backwards compatible because the `partition_size` parameter has a default value.

## Testing
- CI

### CODE REVIEW

**Review by aalavian — APPROVED** [review]
Thanks @zhenyu , could you please bump up version (https://github.com/woven-planet/wicker/blob/main/VERSION) before merging?

**Review by marccarre — APPROVED** [review]
LGTM @zhenyu! Thanks for the change, readable PR, and good description of the rationale. 🙇🏻‍♂️

**Comment by zhenyu** [comment]
> Thanks @zhenyu , could you please bump up version (https://github.com/woven-planet/wicker/blob/main/VERSION) before merging?

Thanks @aalavian for reminder! done

**Comment by zhenyu** [comment]
> LGTM @zhenyu! Thanks for the change, readable PR, and good description of the rationale. 🙇🏻‍♂️

Thanks for the approval:)!

**Pull request merged**
