### PR TITLE
Maintenance to CODEOWNERS file

### PR DESCRIPTION
**Pull request by convexquad**
@aalavian and @marccarre I realized I need to be able to review and approve PRs to Wicker. I would really prefer if this was not true! However, I think it is necessary unfortunately.

The cloud is moving definitively towards FUSE-mounted storage access (i.e. the data appears as a local volume in your compute instance instead of using a cloud-specific data access API like `boto3`). This has already happened for AWS (with `mountpoint-s3` plus S3 Express One Zone) and in GCP (and it is happening in all major clouds). I need to be able to review fixes and upload scripts that will keep Wicker compatible with locally-mounted cloud storage and multi-cloud.

I'll make sure that PRs meet our coding quality standards; are fully tested with both unit tests and cloud runs; and are backwards compatible with existing code. Also, we are only going to work on maintenance fixes and multi-cloud compatibility for Wicker - we are not planning on writing new features for it or otherwise changing its roadmap.

### CODE REVIEW

**Comment by convexquad** [comment]
@aalavian @marccarre let me get a review for this change!

**Comment by convexquad** [comment]
Pardon in my first version I misread the diff from https://github.com/woven-planet/wicker/pull/63/files as a deletion. This PR is fixed now to just add me and that is all @aalavian @marccarre .

**Review by marccarre — APPROVED** [review]

**Comment by pickles-bread-and-butter** [comment]
@convexquad can you change my gh name in this to @pickles-bread-and-butter . I had to change it and now the owners file isn't valid.

**Comment by convexquad** [comment]
(Merging as I have discussed with Marc and Alborz)

**Pull request merged**
